core/urls.py
from django.urls import path, include

from .views import IndexTemplateView


core_patterns = ([
	path('', IndexTemplateView.as_view(), name='index'),
], 'core')

cuentas/urls.py
from django.urls import path
from .views import (
	CuentaListView,
	CuentaDetailView,
	CuentaCreateView,
)


cuentas_patterns = ([
	path('listar/', CuentaListView.as_view(), name='listar'),
	path('<slug:pk>/detalle/', CuentaDetailView.as_view(), name='detalle'),
	path('crear/', CuentaCreateView.as_view(), name='crear'),
], 'cuentas')

cuentas/models.py
# -*- coding: utf-8 -*-
import uuid
from datetime import timedelta

from django.core.validators import MinValueValidator
from django.db import (
    models,
    transaction, 
    IntegrityError
)
from django.db.models.signals import post_save
from django.dispatch import receiver

from core.behaviors import BasicTimeStampable
from core.utils import random_with_N_digits
from grupos.models import Grupo
from pagos.models import (
    Calendario,
    PagoIndividual,
)

from .behaviors import AccountCodeable


class Cuenta(BasicTimeStampable, AccountCodeable):
    '''Administra la información de las Cuentas.'''

    ESTATUS_DESEMBOLSADA = 'DESEMBOLSADA'
    ESTATUS_CERRADA = 'CERRADA'

    ESTATUS_OPCIONES = (
    	(ESTATUS_DESEMBOLSADA, 'Cuenta Desembolsada'),
    	(ESTATUS_CERRADA, 'Cuenta Cerrada'),
	)

    NUMERO_DE_PAGOS_DEFAULT = 4

    NUMERO_DE_PAGOS_OPCIONES = [
        (number, number) for number in range(1, 11)
    ]

    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4, 
        editable=False
    )
    grupo = models.ForeignKey(
        Grupo,
        on_delete=models.PROTECT,
        help_text="Grupo al que pertenece la cuenta"
    )
    estatus = models.CharField(
        max_length=12,
        choices=ESTATUS_OPCIONES,
        default=ESTATUS_DESEMBOLSADA,
        help_text="Estatus de la cuenta"
    )
    monto = models.DecimalField(
    	max_digits=15,
    	decimal_places=2,
        validators=[
            MinValueValidator(0)
        ],
        help_text='Monto de la cuenta'
    )    
    calendario = models.ForeignKey(
        Calendario,
        on_delete=models.PROTECT,
        related_name='cuenta',
        help_text="Calendario de pagos"
    )
    numero_pagos = models.PositiveSmallIntegerField(
        choices=NUMERO_DE_PAGOS_OPCIONES,
        default=NUMERO_DE_PAGOS_DEFAULT,
        help_text='Numero de pagos de la cuenta'
    )

    @classmethod
    def generar_codigo_cuenta(cls):
        '''
        Genera un codigo unico de identificación
        constituido por 5 digitos irrepetibles.
        '''

        codigo_cuenta = random_with_N_digits(5)
        while cls.objects.filter(codigo=codigo_cuenta).exists():
            codigo_cuenta = random_with_N_digits(5)
        return codigo_cuenta

    def calcular_monto_total_pagado(self): 
        '''Calcula el monto total de la cuenta.'''
        monto = 0
        pagos_individuales = self.calendario.pagos.all()
        for pago_individual in pagos_individuales:
            for abono in pago_individual.abonos.all():
                monto += abono.monto
        return monto

    @property    
    def puede_cerrarse(self):
        '''Indica si se cubrio el monto total'''
        if self.monto == self.calcular_monto_total_pagado():
            return True
        else:
            return False

    def cerrar(self):
        '''Marca la cuenta con estatus cerrada.'''
        self.estatus = Cuenta.ESTATUS_CERRADA
        self.save()

    def __str__(self):
        return '%s - %s' % (self.grupo, self.estatus)

    class Meta:
         ordering = ['-created']
         verbose_name = "Cuenta"
         verbose_name_plural = "Cuentas"


@receiver(post_save, sender=Cuenta)
def perform_create(sender, instance, created, **kwargs):
    
    if created:
        # generar codigo simple de indentificación
        instance.codigo = Cuenta.generar_codigo_cuenta()
        instance.save()
        
        # crear pagos individuales para el calendario
        periodo_pago = instance.calendario.periodo_pago
        fecha_esperada  = instance.created + timedelta(days=periodo_pago) 
        for _ in range(0, instance.numero_pagos):
            pago_individual = PagoIndividual.crear(
                monto_individual = instance.calendario.monto_individual,
                fecha = fecha_esperada,
                user_create = instance.user_create
            )
            fecha_esperada += timedelta(days=periodo_pago) 
            instance.calendario.pagos.add(pago_individual)

pagos/models.py
# -*- coding: utf-8 -*-
import uuid
from datetime import date

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from core.behaviors import (
    TimeStampable,
    BasicTimeStampable
)
from core.validators import validate_date


class Calendario(BasicTimeStampable):
    '''
    Administra la información del calendario de pagos.
    Al crearse una cuenta se crea un calendario de pagos.
    El monto del la cuenta se divide entre el numero 
    de pagos individuales que tendra.
    '''

    PAGO_SEMANAL = 7
    PAGO_QUINCENAL = 15
    PAGO_MENSUAL = 30

    PERIDO_PAGO_OPCIONES = (
        (PAGO_SEMANAL, 'SEMANAL'),
        (PAGO_QUINCENAL, 'QUINCENAL'),
        (PAGO_MENSUAL, 'MENSUAL'),
    )

    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4, 
        editable=False
    )
    numero_pagos = models.PositiveSmallIntegerField()
    pagos = models.ManyToManyField(
        'PagoIndividual',
        related_name='calendario',
        help_text="Pagos individuales del calendario"
    )
    periodo_pago = models.PositiveSmallIntegerField(
        choices=PERIDO_PAGO_OPCIONES,
        default=PAGO_SEMANAL,
        help_text='Periodo de pago'
    )

    @property
    def monto_individual(self):
        cuenta = self.cuenta.all().first()
        monto_individual = cuenta.monto / self.numero_pagos
        return monto_individual
    
    @classmethod
    def crear(cls, numero_pagos, user_create):
        '''
        Crea un nuevo calendario con base en 
        un numero de pagos y el usuario .
        '''

        calendar = cls(
            numero_pagos = numero_pagos,
            user_create = user_create
        )
        calendar.save()
        return calendar

    def __str__(self):
        return '%s' % self.id

    class Meta:
        ordering = ['-created']
        verbose_name = "Calendario"
        verbose_name_plural = "Calendarios"


class PagoIndividual(BasicTimeStampable):
    '''Administra la información de pagos individuales.'''

    ESTATUS_PENDIENTE = 'PENDIENTE'
    ESTATUS_PARCIAL = 'PARCIAL'
    ESTATUS_PAGADO = 'PAGADO'

    ESTATUS_OPCIONES = (
    	(ESTATUS_PENDIENTE, 'Pago PENDIENTE'),
    	(ESTATUS_PARCIAL, 'Pago PARCIAL'),
    	(ESTATUS_PAGADO, 'Pago PAGADO'),
	)

    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4, 
        editable=False
    )
    monto_individual = models.DecimalField(
    	max_digits=15,
    	decimal_places=2,
        validators=[
            MinValueValidator(0)
        ],
        help_text='Monto individual del pago'
    )  
    fecha = models.DateField(
    	help_text='Fecha esperada de pago',
        validators=[validate_date],
	)
    estatus = models.CharField(
        max_length=12,
        choices=ESTATUS_OPCIONES,
        default=ESTATUS_PENDIENTE,
        help_text="Estatus del pago"
    )
    abonos = models.ManyToManyField(
        'Abono',
        related_name='pago_individual',
        help_text="Abonos a pagos individuales"
    )

    @classmethod
    def crear(cls, monto_individual, fecha, user_create):
        individual_payment = cls(
            monto_individual = monto_individual,
            fecha = fecha,
            user_create = user_create
        )
        individual_payment.save()
        return individual_payment

    @property
    def esta_atrasado(self):
        if date.today() > self.fecha:
            return True
        return False

    def calcular_monto_abonos(self):
        abonos = 0
        for abono in self.abonos.all():
            abonos += abono.monto
        return abonos     

    def calcular_numero_abonos(self):
        return self.abonos.all().count()

    def calcular_monto_liquidar(self):
        abonos = self.calcular_monto_abonos()
        return self.monto_individual - abonos

    def abono_bloqueado(self):
        monto_liquidar = self.calcular_monto_liquidar()
        if int(monto_liquidar) == 0:
            return True
        return False

    def __str__(self):
        return '%s - %s - %s' % (
        	self.fecha, 
        	self.monto_individual, 
        	self.estatus
    	)

    class Meta:
        ordering = ['created']
        verbose_name = "Pago Individual"
        verbose_name_plural = "Pagos Individuales"


class Abono(BasicTimeStampable):
    '''
    Administra la información de 
    abonos a pagos indivuales.
    '''

    id = models.UUIDField(
        primary_key=True, 
        default=uuid.uuid4, 
        editable=False
    )
    monto = models.DecimalField(
        max_digits=15,
        decimal_places=2,
        validators=[
            MinValueValidator(1)
        ],
        help_text='Monto del abono'
    )

    def __str__(self):
        return str(self.monto)

    class Meta:
        ordering = ['created']
        verbose_name = "Abono"
        verbose_name_plural = "Abonos"

cuentas/forms.py
# -*- coding: utf-8 -*-
from django import forms 

from grupos.models import Grupo
from .models import Cuenta


class CuentaCreateForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Cuenta
        fields = [
            'grupo',
            'monto',
            'numero_pagos',
        ]

cuentas/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    FormView,
)

from braces.views import GroupRequiredMixin

from .constants import CREATE_ACCOUNT_INDICATION
from djangosearchpaginationplus.views import (
    DinamicPaginationMixin, 
    SearchMixin
)
from pagos.models import Calendario
from .forms import CuentaCreateForm
from .models import Cuenta


class CuentaListView(GroupRequiredMixin, DinamicPaginationMixin,
                      SearchMixin, ListView):
    group_required = ('administrador_front', )
    model = Cuenta
    template_name = 'cuentas/list.html'

    def get_filter(self, queryset):
        search = self.get_search()

        if search:
            queryset = queryset.filter(
                Q(grupo__nombre__icontains=search) |
                Q(estatus__icontains=search) |
                Q(monto__icontains=search) |
                Q(saldo__icontains=search) 
            )
        return queryset


class CuentaDetailView(GroupRequiredMixin, DetailView):
    group_required = ('administrador_front', )
    model = Cuenta
    template_name = 'cuentas/detail.html'


class CuentaCreateView(GroupRequiredMixin, CreateView):
    group_required = ('administrador_front')
    form_class = CuentaCreateForm
    template_name = 'core/form.html'
    success_msg = 'Cuenta creada exitosamente'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        messages.warning(self.request, CREATE_ACCOUNT_INDICATION)
        data = {
            'title': 'Crear Cuenta',
            'button_legend': 'Crear cuenta'
        }
        context.update(data)
        return context

    def form_valid(self, form):
        # create new calendar
        new_calendar = Calendario.crear(
            numero_pagos=form.instance.numero_pagos,
            user_create = self.request.user
        )
        form.instance.calendario = new_calendar
        form.instance.user_create = self.request.user
        form.instance.saldo = form.instance.monto
        messages.success(
            self.request, 
            self.success_msg
        )
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'cuentas:detalle', 
            kwargs = {'pk': self.object.pk }
        )

cuentas/templates/cuentas/detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Detalle de cuenta{% endblock %}
{% block content %} 
    <main role="main">
        <div class="container mt-3">

            <div class="row">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Información de cuenta</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Código de la cuenta</th>
                            <td>{{cuenta.codigo}}</td>
                            <td></td>
                        </tr>                        
                        <tr>
                            <th scope="row">Estatus de la cuenta</th>
                            <td>{{cuenta.estatus}}</td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">Nombre del Grupo</th>
                            <td>{{cuenta.grupo.nombre}}</td>
                            <td></td>
                        </tr>                        
                        <tr>
                            <th scope="row">Código del grupo</th>
                            <td>{{cuenta.grupo.codigo}}</td>
                            <td></td>
                        </tr>
                        <tr>
                            <th scope="row">Monto</th>
                            <td>${{cuenta.monto}} MXN</td>
                            <td></td>
                        </tr>                        
                        <tr>
                            <th scope="row">Saldo Pagado</th>
                            <td>$ {{cuenta.calcular_monto_total_pagado}} MXN</td>
                            <td></td>
                        </tr>                        
                        <tr>
                            <th scope="row">Numero de pagos</th>
                            <td>{{cuenta.numero_pagos}} Pagos individuales</td>
                            <td></td>
                        </tr>                            
                        <tr>
                            <th scope="row">Monto individual</th>
                            <td>${{cuenta.calendario.monto_individual}} MXN</td>
                            <td></td>
                        </tr>                        
                        <tr>
                            <th scope="row">Periodo de pagos</th>
                            <td>{{cuenta.calendario.get_periodo_pago_display}}</td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div><!-- /row -->                

            <div class="row">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col">Información del Calendario de pagos</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>    
                        <tr>
                            <th scope="row">Fecha</th>
                            <th scope="row">Monto</th>
                            <th scope="row">Abonado</th>
                            <th scope="row"># de abonos</th>
                            <th scope="row">Liquida</th>
                            <th scope="row">Estatus</th>
                            <th scope="row">Atrasado</th>
                            <th scope="row">Opciones</th>
                        </tr>
                        {% for pago_individual in cuenta.calendario.pagos.all %}
                            <tr>
                                <td>{{pago_individual.fecha}}</td>
                                <td>${{pago_individual.monto_individual}} MXN</td>
                                <td>${{pago_individual.calcular_monto_abonos}} MXN</td>
                                <td>{{pago_individual.calcular_numero_abonos}}</td>
                                <td>${{pago_individual.calcular_monto_liquidar}} MXN</td>
                                <td>{{pago_individual.estatus}}</td>
                                <td>{{pago_individual.esta_atrasado|yesno:"SI,NO"}}</td>
                                <td>
                                    {% if not pago_individual.abono_bloqueado %}
                                        <a href="{% url 'pagos:crear' pk_pago=pago_individual.pk pk_cuenta=cuenta.pk %}">Abonar
                                            <img border="0" alt="Abonar" src="{% static 'img/icons/plus-circle.svg' %}">
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div><!-- /row -->

            <div class="row">
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">Información del registro</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Creó</th>
                            <td>{{cuenta.user_create}}</td>
                        </tr>                        
                        <tr>
                            <th scope="row">Fecha de creación </th>
                            <td>{{cuenta.created}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Fecha de ultima actualización </th>
                            <td>{{cuenta.modified}}</td>
                        </tr>
                    </tbody>
                </table>       
            </div><!-- /row -->

            <div class="row mb-4">
                <a href="{% url 'cuentas:listar' %}" class="btn btn-outline-warning btn-block">Regresar</a> 
            </div>

        </div><!-- /container -->
    </main>
{% endblock %}

cuentas/templates/cuentas/list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Lista de cuentas{% endblock %}
{% block content %}
    <main class="container">
        <div class="search">
            {% include 'djangosearchpaginationplus/includes/_search.html' %}
        </div>
        <div class="row">
            <div class="col-sm-3 offset-sm-4"><a href="{% url 'cuentas:crear' %}" class="btn btn-outline-success btn-block">Crear nueva cuenta</a></div>
        </div>
    	<div class="row mt-3 mb-3">
            <div class="col-12 row_table_list">
        		<table class="table table-hover table-striped">
        			<thead>
        				<tr>
        					<th scope="col">Grupo</th>
        					<th scope="col">Estatus</th>
                            <th scope="col">Monto</th>
                            <th scope="col">Saldo</th>
        					<th scope="col">Detalle</th>
        				</tr>
        			</thead>
        			<tbody>
        				{% for cuenta in cuenta_list %}
    	    				<tr>
    	    					<td>{{cuenta.grupo}}</td>
    	    					<td>{{cuenta.estatus}}</td>
    	    					<td>${{cuenta.monto}}</td>
                                <td>${{cuenta.saldo}}</td>
    	    					<td>
                                    <a href="{% url 'cuentas:detalle' cuenta.pk %}">
                                        <img border="0" alt="Detalle" src="{% static 'img/icons/chevron-double-right.svg' %}">
                                    </a>
                                </td>
    	    				</tr>
        				{% endfor %}
        			</tbody>
        		</table>
            </div><!--row col-12 -->
    	</div><!--row mt-5 mb-3 -->
    </main>
	<div class="table-responsive"><!-- pagination -->
	    <div class="col-md-12 col-sm-12 col-xs-12">
	        {% include 'djangosearchpaginationplus/includes/_pagination.html' %}
	    </div>
	</div><!-- /pagination -->
{% endblock %}
{% block javascript %}
	{{ block.super }}
	<script src="{% static 'js/django_search_pagination_plus/djangosearchpaginationplus.js' %}"></script>
{% endblock %}